// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/ihcsim/bluelens/design
// --out=$(GOPATH)/src/github.com/ihcsim/bluelens/server
// --version=v1.1.0
//
// API "bluelens": Application Contexts
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"github.com/goadesign/goa"
	"golang.org/x/net/context"
	"strconv"
)

// ListRecommendationsContext provides the recommendations list action context.
type ListRecommendationsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	MaxCount int
	UserID   string
}

// NewListRecommendationsContext parses the incoming request URL and body, performs validations and creates the
// context used by the recommendations controller list action.
func NewListRecommendationsContext(ctx context.Context, service *goa.Service) (*ListRecommendationsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	rctx := ListRecommendationsContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramMaxCount := req.Params["maxCount"]
	if len(paramMaxCount) > 0 {
		rawMaxCount := paramMaxCount[0]
		if maxCount, err2 := strconv.Atoi(rawMaxCount); err2 == nil {
			rctx.MaxCount = maxCount
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("maxCount", rawMaxCount, "integer"))
		}
	}
	paramUserID := req.Params["userID"]
	if len(paramUserID) > 0 {
		rawUserID := paramUserID[0]
		rctx.UserID = rawUserID
	}
	return &rctx, err
}

// OKAll sends a HTTP response with status code 200.
func (ctx *ListRecommendationsContext) OKAll(r *BluelensRecommendationsAll) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OK sends a HTTP response with status code 200.
func (ctx *ListRecommendationsContext) OK(r *BluelensRecommendations) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// FollowsUserContext provides the user follows action context.
type FollowsUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	FolloweeID string
	FollowerID int
}

// NewFollowsUserContext parses the incoming request URL and body, performs validations and creates the
// context used by the user controller follows action.
func NewFollowsUserContext(ctx context.Context, service *goa.Service) (*FollowsUserContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	rctx := FollowsUserContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramFolloweeID := req.Params["followeeID"]
	if len(paramFolloweeID) > 0 {
		rawFolloweeID := paramFolloweeID[0]
		rctx.FolloweeID = rawFolloweeID
	}
	paramFollowerID := req.Params["followerID"]
	if len(paramFollowerID) > 0 {
		rawFollowerID := paramFollowerID[0]
		if followerID, err2 := strconv.Atoi(rawFollowerID); err2 == nil {
			rctx.FollowerID = followerID
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("followerID", rawFollowerID, "integer"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *FollowsUserContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// ListensUserContext provides the user listens action context.
type ListensUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	MusicID int
	UserID  string
}

// NewListensUserContext parses the incoming request URL and body, performs validations and creates the
// context used by the user controller listens action.
func NewListensUserContext(ctx context.Context, service *goa.Service) (*ListensUserContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	rctx := ListensUserContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramMusicID := req.Params["musicID"]
	if len(paramMusicID) > 0 {
		rawMusicID := paramMusicID[0]
		if musicID, err2 := strconv.Atoi(rawMusicID); err2 == nil {
			rctx.MusicID = musicID
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("musicID", rawMusicID, "integer"))
		}
	}
	paramUserID := req.Params["userID"]
	if len(paramUserID) > 0 {
		rawUserID := paramUserID[0]
		rctx.UserID = rawUserID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ListensUserContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}
