// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/ihcsim/bluelens/design
// --out=$(GOPATH)/src/github.com/ihcsim/bluelens/server
// --version=v1.1.0
//
// API "bluelens": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
