// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/ihcsim/bluelens/design
// --out=$(GOPATH)/src/github.com/ihcsim/bluelens/cmd/blued
// --version=v1.1.0
//
// API "bluelens": Application Contexts
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"github.com/goadesign/goa"
	"golang.org/x/net/context"
	"strconv"
)

// GetMusicContext provides the music get action context.
type GetMusicContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewGetMusicContext parses the incoming request URL and body, performs validations and creates the
// context used by the music controller get action.
func NewGetMusicContext(ctx context.Context, service *goa.Service) (*GetMusicContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	rctx := GetMusicContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *GetMusicContext) OK(r *BluelensMusic) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKLink sends a HTTP response with status code 200.
func (ctx *GetMusicContext) OKLink(r *BluelensMusicLink) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *GetMusicContext) NotFound(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// RecommendRecommendationsContext provides the recommendations recommend action context.
type RecommendRecommendationsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	MaxCount int
	UserID   string
}

// NewRecommendRecommendationsContext parses the incoming request URL and body, performs validations and creates the
// context used by the recommendations controller recommend action.
func NewRecommendRecommendationsContext(ctx context.Context, service *goa.Service) (*RecommendRecommendationsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	rctx := RecommendRecommendationsContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramMaxCount := req.Params["maxCount"]
	if len(paramMaxCount) > 0 {
		rawMaxCount := paramMaxCount[0]
		if maxCount, err2 := strconv.Atoi(rawMaxCount); err2 == nil {
			rctx.MaxCount = maxCount
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("maxCount", rawMaxCount, "integer"))
		}
		if rctx.MaxCount < 0 {
			err = goa.MergeErrors(err, goa.InvalidRangeError(`maxCount`, rctx.MaxCount, 0, true))
		}
	}
	paramUserID := req.Params["userID"]
	if len(paramUserID) > 0 {
		rawUserID := paramUserID[0]
		rctx.UserID = rawUserID
	}
	return &rctx, err
}

// OKAll sends a HTTP response with status code 200.
func (ctx *RecommendRecommendationsContext) OKAll(r *BluelensRecommendationsAll) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OK sends a HTTP response with status code 200.
func (ctx *RecommendRecommendationsContext) OK(r *BluelensRecommendations) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *RecommendRecommendationsContext) NotFound(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// FollowUserContext provides the user follow action context.
type FollowUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	FolloweeID string
	ID         string
}

// NewFollowUserContext parses the incoming request URL and body, performs validations and creates the
// context used by the user controller follow action.
func NewFollowUserContext(ctx context.Context, service *goa.Service) (*FollowUserContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	rctx := FollowUserContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramFolloweeID := req.Params["followeeID"]
	if len(paramFolloweeID) > 0 {
		rawFolloweeID := paramFolloweeID[0]
		rctx.FolloweeID = rawFolloweeID
	}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OKAll sends a HTTP response with status code 200.
func (ctx *FollowUserContext) OKAll(r *BluelensUserAll) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OK sends a HTTP response with status code 200.
func (ctx *FollowUserContext) OK(r *BluelensUser) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKLink sends a HTTP response with status code 200.
func (ctx *FollowUserContext) OKLink(r *BluelensUserLink) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *FollowUserContext) BadRequest(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *FollowUserContext) NotFound(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// GetUserContext provides the user get action context.
type GetUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewGetUserContext parses the incoming request URL and body, performs validations and creates the
// context used by the user controller get action.
func NewGetUserContext(ctx context.Context, service *goa.Service) (*GetUserContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	rctx := GetUserContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OKAll sends a HTTP response with status code 200.
func (ctx *GetUserContext) OKAll(r *BluelensUserAll) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OK sends a HTTP response with status code 200.
func (ctx *GetUserContext) OK(r *BluelensUser) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKLink sends a HTTP response with status code 200.
func (ctx *GetUserContext) OKLink(r *BluelensUserLink) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *GetUserContext) NotFound(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}

// ListenUserContext provides the user listen action context.
type ListenUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID      string
	MusicID string
}

// NewListenUserContext parses the incoming request URL and body, performs validations and creates the
// context used by the user controller listen action.
func NewListenUserContext(ctx context.Context, service *goa.Service) (*ListenUserContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	rctx := ListenUserContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	paramMusicID := req.Params["musicID"]
	if len(paramMusicID) > 0 {
		rawMusicID := paramMusicID[0]
		rctx.MusicID = rawMusicID
	}
	return &rctx, err
}

// OKAll sends a HTTP response with status code 200.
func (ctx *ListenUserContext) OKAll(r *BluelensUserAll) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OK sends a HTTP response with status code 200.
func (ctx *ListenUserContext) OK(r *BluelensUser) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKLink sends a HTTP response with status code 200.
func (ctx *ListenUserContext) OKLink(r *BluelensUserLink) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *ListenUserContext) BadRequest(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ListenUserContext) NotFound(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 404, r)
}
